SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD=$(shell pwd)
VERILOG_SOURCES = $(PWD)/packet_handler.v
TOPLEVEL = packet_handler
COCOTB_TEST_MODULES = tb_cocotb

ifeq ($(WAVES),1)
    export WAVES=1
    COMPILE_ARGS += -D WAVES=1
endif

include $(shell cocotb-config --makefiles)/Makefile.sim
